version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:v1
    build: redisDocker/
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
#  front:
#    build:
#      context: ../frontend
#      dockerfile: ../dockerCompose/frontDocker/Dockerfile
#    ports:
#      - '44444:8080'

#  favourites_service:
#    build:
#      context: ../favouritesService/
#      dockerfile: ../dockerCompose/favouritesDocker/Dockerfile
#    hostname: 'favourites_service'
#    depends_on:
#      - redis
#    ports:
#      - '10000:8080'
#    volumes:
#      - '~/'
#
  shoppingcart_service:
    build:
      context: ../shoppingCartService/
      dockerfile: ../dockerCompose/shoppingCartDocker/Dockerfile
    links:
      - redis
    ports:
      - '10001:8080'
    environment:
      logging.level.org.springframework: DEBUG

  login_service:
    build:
      context: ../loginService/
      dockerfile: ../dockerCompose/loginDocker/Dockerfile
    ports:
      - '10002:8080'
    depends_on:
      - mongodb
    environment:
      - spring_data_mongodb_authentication_database=admin
      - spring_data_mongodb_database=mydatabase
      - spring_data_mongodb_port=27017
      - spring_data_mongodb_host=mongodb
      - spring_data_mongodb_auto-index-creation=true
      - logging.level.org.springframework=DEBUG
      #- spring_data_mongodb_username=root
      #- spring_data_mongodb_password=root



  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root


#  product_service:
#    build:
#      context: ../productsService/
#      dockerfile: ../dockerCompose/productsDocker/Dockerfile
#    ports:
#      - '10003:8080'
#    depends_on:
#      - mongodb2
#    environment:
#      - spring_data_mongodb_authentication_database=admin
#      - spring_data_mongodb_database=mydatabase
#      - spring_data_mongodb_port=27017
#      - spring_data_mongodb_host=mongodb2
#      - spring_data_mongodb_auto-index-creation=true
#
#  mongodb2:
#    image: mongo
#    container_name: "mongodb2"
#    ports:
#      - 27016:27017
#    volumes:
#      - mongo-data2:/data/db
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=root

  varnish-products:
    image: varnish:stable
    container_name: varnish-products
    volumes:
      - "./default.vcl:/etc/varnish/default.vcl"
    ports:
      - "80:80"
    tmpfs:
      - /var/lib/varnish:exec
    environment:
      - VARNISH_SIZE=2G
    command: "-p default_keep=300"
    depends_on:
      - product_service

volumes:
  mongo-data:
    driver: local
  mongo-data2:
    driver: local
  redis_data:
